name: 'codeploy-lambda'
description: 'Deploy lambda function(s) using AWS CodeDeploy'
author: 'Geert Wille'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'upload-cloud'
  color: 'blue'

# Define your inputs here.
inputs:
  applicationName:
    description: 'The name of the CodeDeploy application'
    required: true
  deploymentGroupName:
    description: 'The name of the CodeDeploy deployment group'
    required: false
  deploymentConfigName:
    description: 'The name of the CodeDeploy deployment config'
    required: false
    default: 'CodeDeployDefault.LambdaAllAtOnce'
  description:
    description: 'The description of the deployment'
    required: false
  tagKey:
    description: 'The key of the tag'
    required: true
  tagValues:
    description: 'The values of the tag'
    required: true

# Define your outputs here.
outputs:
  deploymentId:
    description: 'The ID of the deployment'
  status:
    description: 'The status of the deployment'

runs:
  using: node20
  main: dist/index.js
